### PR TITLE
Create an option for standalone progressbar

### PR DESCRIPTION
**Pull request by Gozala**
If browser.html is passed query argument `progressbar=standalone` it will not animate progress with regular update loop, instead it will spawn up separate animation frame loop & update element.style directly without causing update or render loops.

### CODE REVIEW

**Comment by paulrouget** [comment]
From *682ms*, with the standalone code we go down to *493ms* and with a rAF workaround down to *391ms*. 

This is getting better :)

**Comment by Gozala** [comment]
> From 682ms, with the standalone code we go down to 493ms and with a rAF workaround down to 391ms.

This is little confusing in what time frame are those numbers ? Just looking at the numbers I get an impression it's not so great.

BTW I also noticed that there are bunch of other events going on during page loads which could be a reason it's still not very fast.

**Comment by paulrouget** [comment]
XXXXms per second on a 20s time of sampling while page is loading.
And yes, it's not great.

Electron (4 processes). Same order of magnitude.

Before your patch:
```
Electron 314.45
Electron  93.25        
Electron 77.40
Electron  6.10        
```

After:
```
Electron 194.67
Electron 95.09
Electron 78.91
Electron 6.79
```

**Comment by paulrouget** [comment]
> BTW I also noticed that there are bunch of other events going on during page loads which could be a reason it's still not very fast.

Like?

**Comment by paulrouget** [comment]
r+

**Comment by Gozala** [comment]
> Like?

`LoadStart, LocationChange, Connected, MetaChanged, OverflowChange, TitleChange, IconChange, ....`

**Pull request merged**
