### PR TITLE
Update tiles displayed on dashboard.

### PR DESCRIPTION
**Pull request by Gozala**
Update links according to: https://github.com/metajack/servo.org/blob/demo-newtab/bhtml-newtab/newtab.html

@metajack I have updated images to fit them better / match styling of tiles, please speak up if that's not ok. I also have filled one empty slot with link to rust, again let me know if you disagree.

screen shot 2016-06-15 at 2 20 51 pm

Links in the bottom line presume that demos can be found under following urls:

https://servo.org/bhtml-newtab/webrender-demos/moire.html
https://servo.org/bhtml-newtab/webrender-demos/spheres.html
https://servo.org/bhtml-newtab/webrender-demos/transparent_rects.html
https://servo.org/bhtml-newtab/webrender-demos/menus.html

I think it makes more sense than bundling them along with browser.html and source suggests it will merge into `servo.org`, is it ?

@metajack There is also `menus.html` demo missing in the source.

---
This change is [Reviewable](https://reviewable.io/reviews/browserhtml/browserhtml/1091)

### CODE REVIEW

**Comment by paulrouget** [comment]
r=me

**Comment by metajack** [comment]
r=me

We may make a change but this is definitely really close. I'll make sure bhtml-newtab is updated on servo.org.

**Comment by metajack** [comment]
Oh, you might want to push this change there too so that the pages match.

**Comment by Gozala** [comment]
> Oh, you might want to push this change there too so that the pages match.

Sure I'll send pull with new tiles and added tile to rust to your fork.

**Comment by Gozala** [comment]
> Oh, you might want to push this change there too so that the pages match.

@metajack I've send pull your way https://github.com/metajack/servo.org/pull/1

**Pull request merged**
