### PR TITLE
Report non-pipeline panics

### LINKED ISSUE #1182: Handle non-pipeline thread panics in the root document.
Servo will dispatch mozbrowsererror's on the root document for non-pipeline thread panics. We should handle them and hook them into existing error reporter code base.

### PR DESCRIPTION
**Pull request by Gozala**
Fixes #1182

### CODE REVIEW

**Comment by paulrouget** [comment]
Is it possible to test a non-pipeline panic?

**Comment by paulrouget** [comment]
Looks good to me, but I'd like to test.

**Comment by paulrouget** [comment]
Just saw https://github.com/servo/servo/issues/12727

**Comment by Gozala** [comment]
Let's land, even though we can't test cause in worst case it just won't report issues in best case it will work as expected ;)

**Pull request merged**
