### PR TITLE
Changing Flags to Options

### PR DESCRIPTION
**Pull request by Coder206**
This PR renames the type `Flags` to `Options`

### CODE REVIEW

**Comment by Coder206** [comment]
@Gozala Could I get a little guidance here?

**Comment by Gozala** [comment]
@Coder206 It seems that flow caught some type mismatches you can check out errors by following a _details_ link.

**Comment by Gozala** [comment]
Ok looking at errors:

```
src/browser/Navigators.js:44
 44:   | { type: "Deck", deck: Deck.Action<Navigator.Action, Navigator.Flags> }
                                                             ^^^^^^^^^^^^^^^ Flags. Property not found in
 13: import * as Navigator from "./Navigators/Navigator"
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ exports of "./Navigators/Navigator"
src/browser/Navigators.js:95
 95:   (action:Deck.Action<Navigator.Action, Navigator.Flags>):Action => {
                                             ^^^^^^^^^^^^^^^ Flags. Property not found in
 13: import * as Navigator from "./Navigators/Navigator"
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ exports of "./Navigators/Navigator"
src/browser/Navigators/Navigator.js:35
 35:   { output: Output.Options
                 ^^^^^^^^^^^^^^ Options. Property not found in
 15: import * as Output from "./Navigator/WebView";
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ exports of "./Navigator/WebView"
src/browser/Navigators/Navigator.js:39
 39:   , overlay?: Overlay.Options
                   ^^^^^^^^^^^^^^^ Options. Property not found in
 13: import * as Overlay from "./Navigator/Overlay";
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ exports of "./Navigator/Overlay"
src/browser/Navigators/Navigator.js:40
 40:   , assistant?: Assistant.Options
                     ^^^^^^^^^^^^^^^^^ Options. Property not found in
 12: import * as Assistant from "./Navigator/Assistant";
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ exports of "./Navigator/Assistant"
```

There seems to be few locations where still `Flags` are referred instead of `Options`.

**Comment by Coder206** [comment]
@Gozala Is there a way for me to compile browserhtml on my computer?

**Comment by Gozala** [comment]
> @Gozala Is there a way for me to compile browserhtml on my computer?

Yes see details in [readme](https://github.com/browserhtml/browserhtml#developing-the-front-end) you can replace `./mach run -r --` with `/Applications/Servo.app/Contents/MacOS/servo` instead.

To test that your changes are not breaking anything you can run `npm test` and look at the output, that's the same output you see in travis.

**Comment by Coder206** [comment]
@Gozala Thank you so much! I just completed a build with no errors when running `npm test`!

**Comment by Gozala** [comment]
@Coder206 Great! I am afraid master has moved on since though and you would need to merge it in or rebase your changes so they'll be mergeable. Unfortunately there has being some changes that make merge or rebase fail. You could try following to work it around:

```
git checkout -b Options-backup # create backup in case
git checkout - # switch back
git diff 0eb45f9 > options.patch # generate patch from your changes
```

Update paths in `options.patch`

```
get fetch upstream
git reset upstream/master --hard # remove your changes
git apply options.patch # apply your changes back
```

I can help you out in slack channel if you run into problems with this.

**Comment by Coder206** [comment]
@gozala Thank you very much for taking time out of your evening to help me with this issue. It was much appreciated!

**Comment by Coder206** [comment]
Fixes #1050

**Pull request merged**
